---
title: "Type 2 Diabetes in Pima Native Americans"
author: "Brian Burrows, Eric Sellew, Yonas Shiferaw, and Kelly Yang"
date: "12/3/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mosaic)
library(ggplot2)
library(tidyverse)
library(pROC)
library(rpart)
library(partykit)
```

## R Markdown

```{r}
pima <- read.csv("https://pmatheson.people.amherst.edu/Pima.dat", header=FALSE)
colnames(pima) <- c("PRG", "PLASMA", "BP", "THICK", "INSULIN", "BODY", "PEDIGREE", "AGE", "RESPONSE")
```


## Prevalence of Diabetes in the Dataset

```{r}
tally(pima$RESPONSE)
268/(500+268)
#Approximately 35% of the individual females in this sample have diabetes.
```


```{r}
filteredpima <- filter(pima,PLASMA>0,BP>0,THICK>0,BODY>0,INSULIN>0)
#We noticed biological impossibilities in the data, such as blood pressures of 0. Since it is not possible to distinguish true zeros from non-entries, we removed all entries that had zeros in PLASMA, BP, THICK, BODY, and INSULIN.
```


```{r}
tally(filteredpima$RESPONSE)
262/(262+130)
#Approximately 67% of the individual females in the filtered dataset have diabetes.
```


## EDA

```{r}
summary(filteredpima)
histogram(~PRG, data=filteredpima) #PRG is skewed to the right.
histogram(~PLASMA, data=filteredpima) #Follows a somewhat normal distribution.
histogram(~BP, data=filteredpima) #Also somewhat bell-shaped.
histogram(~THICK, data=filteredpima) #Mostly normal distribution.
histogram(~INSULIN, data=filteredpima) #Skewed to the right.
histogram(~BODY, data=filteredpima) #Somewhat normal distribution, but is slightly skewed to the right.
histogram(~PEDIGREE, data=filteredpima) #Skewed to the right.
histogram(~AGE, data=filteredpima) #Skewed to the right.
```


## Plots

```{r}
pima_age <- pima %>%
  mutate(RESPONSE = ifelse(RESPONSE == 0, "Non-Diabetic", "Diabetic"))%>%
  group_by(AGE, RESPONSE) %>%
  summarize(response_total = n())

ggplot(pima_age, aes(x=AGE, y=response_total, fill=factor(RESPONSE))) + geom_bar(stat="identity", position = "dodge")
```


```{r}
pima_bp <- pima %>%
  mutate(RESPONSE = ifelse(RESPONSE == 0, "Non-Diabetic", "Diabetic"))%>%
  filter(BP > 0) %>%
  group_by(BP, RESPONSE) %>%
  summarize(response_total = n())
ggplot(pima_bp, aes(x=BP, fill=factor(RESPONSE))) +
  geom_density(alpha=0.5) +
  ylab("Density") +
  xlab("Diastolic Blood Pressure") +
  ggtitle("Relationship between Diabetic and Non-Diabetic Groups and Blood Pressure") +
  scale_fill_manual(legend_title, values=c("Red","Blue"))
```


```{r}
pima_thick <- pima %>%
  mutate(RESPONSE = ifelse(RESPONSE == 0, "Non-Diabetic", "Diabetic"))%>%
  filter(THICK > 0) %>%
  group_by(THICK, RESPONSE) %>%
  summarize(response_total = n())
ggplot(pima_thick, aes(x=THICK, fill=factor(RESPONSE))) +
  geom_density(alpha=0.5) +
  ylab("Density") +
  xlab("Triceps Skin Fold Thickness") +
  ggtitle("Relationship between Diabetic and Non-Diabetic Groups and Triceps Skin Fold Thickness") +
  scale_fill_manual(legend_title, values=c("Red","Blue"))
```


```{r}
pima_plasma <- pima %>%
  mutate(RESPONSE = ifelse(RESPONSE == 0, "Non-Diabetic", "Diabetic"))%>%
  filter(PLASMA > 0) %>%
  group_by(PLASMA, RESPONSE) %>%
  summarize(response_total = n())
ggplot(pima_plasma, aes(x=PLASMA, fill=factor(RESPONSE))) +
  geom_density(alpha=0.5) +
  ylab("Density") +
  xlab("Plasma Glucose Concentration in Saliva") +
  ggtitle("Relationship between Diabetic and Non-Diabetic Groups and Plasma Glucose Concentration in Saliva") +
  scale_fill_manual(legend_title, values=c("Red","Blue"))
```


```{r}
pima_insulin <- pima %>%
  mutate(RESPONSE = ifelse(RESPONSE == 0, "Non-Diabetic", "Diabetic"))%>%
  filter(INSULIN > 0) %>%
  group_by(INSULIN, RESPONSE) %>%
  summarize(response_total = n())
ggplot(pima_insulin, aes(x=INSULIN, fill=factor(RESPONSE))) +
  geom_density(alpha=0.5) +
  ylab("Density") +
  xlab("Two Hours Serum Insulin") +
  ggtitle("Relationship between Diabetic and Non-Diabetic Groups and Two Hours Serum Insulin") +
  scale_fill_manual(legend_title, values=c("Red","Blue"))
```


```{r}
pima_body <- pima %>%
  mutate(RESPONSE = ifelse(RESPONSE == 0, "Non-Diabetic", "Diabetic"))%>%
  filter(BODY > 0) %>%
  group_by(BODY, RESPONSE) %>%
  summarize(response_total = n())
ggplot(pima_body, aes(x=BODY, fill=factor(RESPONSE))) +
  geom_density(alpha=0.5) +
  ylab("Density") +
  xlab("Body Mass Index (Weight/Height)") +
  ggtitle("Relationship between Diabetic and Non-Diabetic Groups and Body Mass Index (Weight/Height)") +
  scale_fill_manual(legend_title, values=c("Red","Blue"))
```


```{r}
pima_pedigree <- pima %>%
  mutate(RESPONSE = ifelse(RESPONSE == 0, "Non-Diabetic", "Diabetic"))%>%
  filter(PEDIGREE > 0) %>%
  group_by(PEDIGREE, RESPONSE) %>%
  summarize(response_total = n())
ggplot(pima_pedigree, aes(x=PEDIGREE, fill=factor(RESPONSE))) +
  geom_density(alpha=0.5) +
  ylab("Density") +
  xlab("Pedigree") +
  ggtitle("Relationship between Diabetic and Non-Diabetic Groups and Pedigree") +
  scale_fill_manual(legend_title, values=c("Red","Blue"))
#Pedigree may not be overly important; however, it does seem that there may be a slight relationship.
```


```{r}
pima_prg <- pima %>%
  mutate(RESPONSE = ifelse(RESPONSE == 0, "Non-Diabetic", "Diabetic"))%>%
  filter(PRG > 0) %>%
  group_by(PRG, RESPONSE) %>%
  summarize(response_total = n())
ggplot(pima_prg, aes(x=PRG, fill=factor(RESPONSE))) +
  geom_density(alpha=0.5) +
  ylab("Density") +
  xlab("Number of Times Pregnant") +
  ggtitle("Relationship between Diabetic and Non-Diabetic Groups and Number of Times Pregnant") +
  scale_fill_manual(legend_title, values=c("Red","Blue"))
```


## Probability Model of Diabetes in an Individual Pima Female

```{r}
#Checking for an interaction.
fmfull<-glm(RESPONSE~., data=filteredpima)
vif(fmfull)
#Although BODY and THICK are both measures of obesity, it seems that the inclusion of an interaction term is unnecessary.
```


```{r}
filteredmodel <- glm(RESPONSE~., data=filteredpima, family=binomial) %>%
  MASS::stepAIC(trace=FALSE)
summary(filteredmodel) #The stepwise logistic regression returned PLASMA, BODY, and PEDIGREE as significant predictors of type 2 diabetes. AGE is also significant at the 10% significance level.
```


## ROC Curve: An Evaluation of the Probability Model

```{r}
predictions <- predict(filteredmodel, data=filteredpima)
plot.roc(filteredpima$RESPONSE, predictions)
auc(filteredpima$RESPONSE, predictions)
```


## Tree

```{r}
filteredmodelpart <- rpart(RESPONSE ~ ., data = filteredpima)
printcp(filteredmodelpart)
pdf("diabetes.pdf", width = 25, height = 12)
plot(as.party(filteredmodelpart))
dev.off()
diabetes <- mutate(filteredpima, fittedtree = predict(filteredmodelpart))
```


```{r}
filteredmodelpart <- rpart(RESPONSE ~ . - AGE - PEDIGREE, data = filteredpima)
printcp(filteredmodelpart)
pdf("diabetes1.pdf", width = 25, height = 12)
plot(as.party(filteredmodelpart))
dev.off()
diabetes <- mutate(filteredpima, fittedtree = predict(filteredmodelpart))
```

